import { Resend } from "resend";
import { jsPDF } from "jspdf";

const resend = new Resend(process.env.RESEND_API_KEY);

function generateTripPDF(trip) {
  const doc = new jsPDF();
  let y = 20;

  doc.setFontSize(16);
  doc.text("TripSheetHQ - Trip Report", 14, y);
  y += 10;

  doc.setFontSize(10);
  doc.text(`Date: ${trip.date || "-"}`, 14, y); y += 6;
  doc.text(`Driver: ${trip.driverName || "-"}`, 14, y); y += 6;
  doc.text(`Trailer #: ${trip.trailerNumber || "-"}`, 14, y); y += 6;
  doc.text(`Pro #: ${trip.proNumber || "-"}`, 14, y); y += 6;
  doc.text(`B/L #: ${trip.blNumber || "-"}`, 14, y); y += 10;

  doc.setFontSize(12);
  doc.text("Pickup", 14, y); y += 6;
  doc.setFontSize(10);
  doc.text(`${trip.pickupCustomer || "-"}, ${trip.pickupCity || "-"}`, 14, y); y += 10;

  doc.setFontSize(12);
  doc.text("Delivery", 14, y); y += 6;
  doc.setFontSize(10);
  doc.text(`${trip.deliveryCustomer || "-"}, ${trip.deliveryCity || "-"}`, 14, y); y += 10;

  doc.setFontSize(12);
  doc.text("Mileage", 14, y); y += 6;
  doc.setFontSize(10);
  doc.text(`Start: ${trip.startOdometer || "-"}   End: ${trip.endOdometer || "-"}   Total: ${trip.totalMiles || "-"} miles`, 14, y);
  y += 10;

  doc.setFontSize(12);
  doc.text("Fuel Purchases", 14, y); y += 6;
  doc.setFontSize(10);
  if (trip.fuelEntries && trip.fuelEntries.length > 0) {
    trip.fuelEntries.forEach((f) => {
      doc.text(`${f.location || "-"} | Qty: ${f.quantity || "-"} | $${f.cost || "0"}`, 14, y);
      y += 6;
    });
  } else {
    doc.text("None", 14, y); y += 6;
  }
  doc.text(`Total Fuel Cost: $${(trip.totalFuelCost || 0).toFixed(2)}`, 14, y);
  y += 10;

  doc.setFontSize(12);
  doc.text("Expenses", 14, y); y += 6;
  doc.setFontSize(10);
  if (trip.expenseEntries && trip.expenseEntries.length > 0) {
    trip.expenseEntries.forEach((exp) => {
      doc.text(`${exp.category || "-"} - ${exp.description || ""} | $${exp.amount || "0"}`, 14, y);
      y += 6;
    });
  } else {
    doc.text("None", 14, y); y += 6;
  }
  doc.text(`Total Expenses: $${(trip.totalExpenseCost || 0).toFixed(2)}`, 14, y);
  y += 10;

  if (trip.notes) {
    doc.setFontSize(12);
    doc.text("Notes", 14, y); y += 6;
    doc.setFontSize(10);
    doc.text(trip.notes, 14, y);
    y += 10;
  }

  doc.setFontSize(8);
  doc.text("Generated by TripSheetHQ", 14, 285);

  return doc.output("arraybuffer");
}

export async function POST(request) {
  try {
    const trip = await request.json();

    const pdfBuffer = generateTripPDF(trip);
    const pdfBase64 = Buffer.from(pdfBuffer).toString("base64");

    const recipients = [
      "royalafricanbeer@gmail.com",
      "zikatransportation@gmail.com",
      "truckergroupinc@gmail.com",
    ];

    if (trip.driverEmail) {
      recipients.push(trip.driverEmail);
    }

    const result = await resend.emails.send({
      from: "TripSheetHQ <onboarding@resend.dev>",
      to: recipients,
      subject: `Trip Report - ${trip.date || "New Trip"} - ${trip.driverName || "Driver"}`,
      html: `<p>A new trip has been submitted.</p>
             <p><strong>Driver:</strong> ${trip.driverName || "-"}<br/>
             <strong>Date:</strong> ${trip.date || "-"}<br/>
             <strong>Route:</strong> ${trip.pickupCustomer || "-"} (${trip.pickupCity || "-"}) → ${trip.deliveryCustomer || "-"} (${trip.deliveryCity || "-"})<br/>
             <strong>Total Miles:</strong> ${trip.totalMiles || "-"}</p>
             <p>See attached PDF for full trip report.</p>`,
      attachments: [
        {
          filename: `trip-${trip.date || "report"}.pdf`,
          content: pdfBase64,
        },
      ],
    });

    return Response.json({ success: true, result });
  } catch (err) {
    console.error("Email send error:", err);
    return Response.json({ success: false, error: err.message }, { status: 500 });
  }
}